package Java_David_J_Eck.chapter5_OOP_Objects;

/**
 * class that implements Readable, including a main() routine that tests the
 * class.
 */
public class Stars implements Readable {
    @Override
    public char readChar() {
        if (Math.random() > 0.02)
            return '*';
        else
            return '\n';
    }

    public static void main(String[] args) {
        Stars stars = new Stars();  // By creating an instance of Stars, you
        // can call the methods defined in the class, including the inherited
        // methods from the Readable interface. In this case, it allows you
        // to call readLine() and readChar().
        for (int i = 0; i < 10; i++) {  // This loop runs 10 times (10 lines
            // will be read and printed to screen)
            String line = stars.readLine(); // Call the default method! Reads
            // a line
            System.out.println(line);   // and prints it.
        }

        /* Output:
        * *******
        * ******************************************************
        * ************************
        * *******************
        * ******************************************************************
        * ********
        * ******************
        * ***************************************
        * ************
        * **********************

        * Process finished with exit code 0

        Summary
        The Readable interface defines a method to read characters and
        provides a default method to read an entire line.
        The Stars class implements Readable and provides a concrete
        implementation for readChar(), generating a sequence of asterisks
        and newlines.
        The main() method tests the Stars class by printing 10 lines
        generated by readLine().
        */

    }   // end of main()
}   // end of class Stars
